name: .NET Core

on: 
  push:
  #schedule:
  # specifiy that the job should be scheduled each 5 minutes
  #  - cron: "0 0 * * *" 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: tests with dotnet
      run: dotnet test --configuration Release
